--
--  Create stock info table
--
CREATE TABLE mapping_service.stocks (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_type      VARCHAR(50) NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()),

    CONSTRAINT unique_stock_type UNIQUE(stock_type)
);

GRANT SELECT, UPDATE, INSERT ON mapping_service.stocks TO ${app_role};
GRANT SELECT ON mapping_service.stocks TO ${app_role_viewer};
