CREATE TABLE mapping_service.networks_data (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_ticker      VARCHAR(50) NOT NULL,
    network_name        TEXT NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT unique_network UNIQUE(network_name, network_ticker)
);

GRANT SELECT, UPDATE, INSERT ON mapping_service.networks_data TO ${app_role};
GRANT SELECT ON mapping_service.networks_data TO ${app_role_viewer};
