CREATE TABLE mapping_service.currency_with_network (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_id         INT NOT NULL,
    network_id          INT NOT NULL,
    contract_address    TEXT DEFAULT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT unique_currency_with_network UNIQUE(tt_currency_id, tt_network_id)
);

GRANT SELECT, UPDATE, INSERT ON mapping_service.currency_with_network TO ${app_role};
GRANT SELECT ON mapping_service.currency_with_network TO ${app_role_viewer};
