CREATE TABLE mapping_service.stocks_currencies_data (
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id                INT NOT NULL,
    currency_ticker         VARCHAR(50) NOT NULL,
    currency_name           TEXT DEFAULT NULL,
    network_ticker          VARCHAR(50) NOT NULL,
    network_name            TEXT DEFAULT NULL,
    contract_address        TEXT DEFAULT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT unique_stock_currency_data UNIQUE(stock_id, currency_ticker, currency_name, network_ticker, network_name)
);

GRANT SELECT, UPDATE, INSERT ON mapping_service.stocks_currencies_data TO ${app_role};
GRANT SELECT ON mapping_service.stocks_currencies_data TO ${app_role_viewer};
