CREATE TABLE mapping_service.currencies_data (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmc_id          INT DEFAULT NULL,
    ticker          VARCHAR(50) NOT NULL,
    name            TEXT NOT NULL,
    enabled         BOOLEAN DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX unique_currency_by_cmc_id
    ON mapping_service.currencies_data (cmc_id)
    WHERE (cmc_id IS NOT NULL);

CREATE UNIQUE INDEX unique_ticker_name
    ON mapping_service.currencies_data (ticker, name)
    WHERE (cmc_id IS NULL);

GRANT SELECT, UPDATE, INSERT ON mapping_service.currencies_data TO ${app_role};
GRANT SELECT ON mapping_service.currencies_data TO ${app_role_viewer};
